version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_PASSWORD: "Moreno2g!"
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
