default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  encoding: unicode
  username: "robertromulus"
  password: <%= Rails.application.credentials.production[:password] %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
